{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "School of Heroes app API",
    "description": "Documentation for server requests and responses of the School of Heroes app",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "servers": [
    { "url": "https://school-heroes-backend.onrender.com/api" }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Events",
      "description": "Events endpoints"
    },
    {
      "name": "Offers",
      "description": "Offers endpoints"
    },
    {
      "name": "Donations",
      "description": "Donations endpoints"
    },
    {
      "name": "Organizers",
      "description": "Organizers endpoints"
    }
  ],
  "paths": {
    "/auth/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "Create a new user",
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationWithEmailResponse"
                }
              }
            }
          },
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "409": {
            "description": "Email already in use"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "Login user with email and password",
        "requestBody": {
          "description": "Login's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginWithEmailRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginWithEmailResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "401": {
            "description": "Invalid Email or password"
          },
          "403": {
            "description": "Email not verified"
          }
        }
      }
    },
    "/auth/google": {
      "post": {
        "tags": ["Auth"],
        "summary": "Login user with Google",
        "requestBody": {
          "description": "Login's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginWithGoogleRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginWithGoogleResponse"
                }
              }
            }
          },
          "202": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginWithGoogleAcceptedResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "401": {
            "description": "Invalid Google token"
          }
        }
      }
    },
    "/auth/apple": {
      "post": {
        "tags": ["Auth"],
        "summary": "Login user with Apple",
        "requestBody": {
          "description": "Login's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginWithAppleRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginWithAppleResponse"
                }
              }
            }
          },
          "202": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginWithAppleAcceptedResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "401": {
            "description": "Invalid Apple token"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "oneOf": [
          { "$ref": "#/components/schemas/RegisterChildWithEmail" },
          { "$ref": "#/components/schemas/RegisterSpeakerWithEmail" },
          { "$ref": "#/components/schemas/RegisterChildWithGoogle" },
          { "$ref": "#/components/schemas/RegisterSpeakerWithGoogle" },
          { "$ref": "#/components/schemas/RegisterChildWithApple" },
          { "$ref": "#/components/schemas/RegisterSpeakerWithApple" }
        ]
      },
      "RegisterChildWithEmail": {
        "type": "object",
        "required": ["method", "email", "password", "role", "name", "phone", "country", "city", "birthday", "file"],
        "properties": {
          "method": {
              "type": "string",
              "enum": ["email"],
              "description": "Registration method: email"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "minLength": 8,
            "maxLength": 24,
            "pattern": "^[a-zA-Z0-9]{8,24}$",
            "description": "User password",
            "example": "Qw52eRty37"
          },
          "role": {
            "type": "string",
            "enum": ["child"],
            "description": "User role"
          },
          "name": {
            "type": "string",
            "minLength": 2,
            "maxLength": 55,
            "description": "User name",
            "example": "Катерина Морська"
          },
          "phone": {
            "type": "string",
            "pattern": "^\\+?\\d{1,4}?[-.\\s]?(\\(?\\d{1,4}\\)?[-.\\s]?)?\\d{1,4}[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$",
            "description": "User's phone",
            "example": "+380123456789"
          },
          "country": {
            "type": "string",
            "pattern": "^[A-Z]{2}$",
            "description": "User's country code. Must be an ISO 3166-1 alpha-2 code.",
            "example": "UA"
          },
          "city": {
            "type": "string",
            "pattern": "^[a-zA-Zа-яА-ЯґҐєЄіІїЇ'’\\s-]{2,50}$",
            "description": "User's city",
            "example": "Київ"
          },
          "birthday": {
            "type": "string",
            "format": "date-time",
            "description": "User's date of birth in ISO 8601 format",
            "example": "2010-01-19T22:00:00Z"
          },
          "file": {
            "type": "string",
            "format": "binary",
            "description": "User avatar file being uploaded (maximum size: 8 MB)"
          }
        }
      },
      "RegisterSpeakerWithEmail": {
        "type": "object",
        "required": ["method", "email", "password", "role", "name", "phone", "country", "city", "activity", "file"],
        "properties": {
          "method": {
              "type": "string",
              "enum": ["email"],
              "description": "Registration method: email"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "minLength": 8,
            "maxLength": 24,
            "pattern": "^[a-zA-Z0-9]{8,24}$",
            "description": "User password",
            "example": "Qw52eRty37"
          },
          "role": {
            "type": "string",
            "enum": ["speaker"],
            "description": "User role"
          },
          "name": {
            "type": "string",
            "minLength": 2,
            "maxLength": 55,
            "description": "User name",
            "example": "Тарас Діброва"
          },
          "phone": {
            "type": "string",
            "pattern": "^\\+?\\d{1,4}?[-.\\s]?(\\(?\\d{1,4}\\)?[-.\\s]?)?\\d{1,4}[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$",
            "description": "User's phone",
            "example": "+380123456789"
          },
          "country": {
            "type": "string",
            "pattern": "^[A-Z]{2}$",
            "description": "User's country code. Must be an ISO 3166-1 alpha-2 code.",
            "example": "UA"
          },
          "city": {
            "type": "string",
            "pattern": "^[a-zA-Zа-яА-ЯґҐєЄіІїЇ'’\\s-]{2,50}$",
            "description": "User's city",
            "example": "Київ"
          },
          "activity": {
            "type": "string",
            "maxLength": 55,
            "description": "User activity",
            "example": "Фермер"
          },
          "file": {
            "type": "string",
            "format": "binary",
            "description": "User avatar file being uploaded (maximum size: 8 MB)"
          }
        }
      },
      "RegisterChildWithGoogle": {
        "type": "object",
        "required": ["method", "google_id", "role", "name", "phone", "country", "city", "birthday", "file"],
        "properties": {
          "method": {
              "type": "string",
              "enum": ["google"],
              "description": "Registration method: google"
          },
          "google_id": {
            "type": "string",
            "description": "User googleId"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "format": "email"
          },
          "role": {
            "type": "string",
            "enum": ["child"],
            "description": "User role"
          },
          "name": {
            "type": "string",
            "minLength": 2,
            "maxLength": 55,
            "description": "User name",
            "example": "Катерина Морська"
          },
          "phone": {
            "type": "string",
            "pattern": "^\\+?\\d{1,4}?[-.\\s]?(\\(?\\d{1,4}\\)?[-.\\s]?)?\\d{1,4}[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$",
            "description": "User's phone",
            "example": "+380123456789"
          },
          "country": {
            "type": "string",
            "pattern": "^[A-Z]{2}$",
            "description": "User's country code. Must be an ISO 3166-1 alpha-2 code.",
            "example": "UA"
          },
          "city": {
            "type": "string",
            "pattern": "^[a-zA-Zа-яА-ЯґҐєЄіІїЇ'’\\s-]{2,50}$",
            "description": "User's city",
            "example": "Київ"
          },
          "birthday": {
            "type": "string",
            "format": "date-time",
            "description": "User's date of birth in ISO 8601 format",
            "example": "2010-01-19T22:00:00Z"
          },
          "file": {
            "type": "string",
            "format": "binary",
            "description": "User avatar file being uploaded (maximum size: 8 MB)"
          }
        }
      },
      "RegisterSpeakerWithGoogle": {
        "type": "object",
        "required": ["method", "google_id", "role", "name", "phone", "country", "city", "activity", "file"],
        "properties": {
          "method": {
              "type": "string",
              "enum": ["google"],
              "description": "Registration method: google"
          },
          "google_id": {
            "type": "string",
            "description": "User googleId"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "format": "email"
          },
          "role": {
            "type": "string",
            "enum": ["speaker"],
            "description": "User role"
          },
          "name": {
            "type": "string",
            "minLength": 2,
            "maxLength": 55,
            "description": "User name",
            "example": "Тарас Діброва"
          },
          "phone": {
            "type": "string",
            "pattern": "^\\+?\\d{1,4}?[-.\\s]?(\\(?\\d{1,4}\\)?[-.\\s]?)?\\d{1,4}[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$",
            "description": "User's phone",
            "example": "+380123456789"
          },
          "country": {
            "type": "string",
            "pattern": "^[A-Z]{2}$",
            "description": "User's country code. Must be an ISO 3166-1 alpha-2 code.",
            "example": "UA"
          },
          "city": {
            "type": "string",
            "pattern": "^[a-zA-Zа-яА-ЯґҐєЄіІїЇ'’\\s-]{2,50}$",
            "description": "User's city",
            "example": "Київ"
          },
          "activity": {
            "type": "string",
            "maxLength": 55,
            "description": "User activity",
            "example": "Фермер"
          },
          "file": {
            "type": "string",
            "format": "binary",
            "description": "User avatar file being uploaded (maximum size: 8 MB)"
          }
        }
      },
      "RegisterChildWithApple": {
        "type": "object",
        "required": ["method", "apple_id", "role", "name", "phone", "country", "city", "birthday", "file"],
        "properties": {
          "method": {
              "type": "string",
              "enum": ["apple"],
              "description": "Registration method: apple"
          },
          "apple_id": {
            "type": "string",
            "description": "User appleId"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "format": "email"
          },
          "role": {
            "type": "string",
            "enum": ["child"],
            "description": "User role"
          },
          "name": {
            "type": "string",
            "minLength": 2,
            "maxLength": 55,
            "description": "User name",
            "example": "Катерина Морська"
          },
          "phone": {
            "type": "string",
            "pattern": "^\\+?\\d{1,4}?[-.\\s]?(\\(?\\d{1,4}\\)?[-.\\s]?)?\\d{1,4}[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$",
            "description": "User's phone",
            "example": "+380123456789"
          },
          "country": {
            "type": "string",
            "pattern": "^[A-Z]{2}$",
            "description": "User's country code. Must be an ISO 3166-1 alpha-2 code.",
            "example": "UA"
          },
          "city": {
            "type": "string",
            "pattern": "^[a-zA-Zа-яА-ЯґҐєЄіІїЇ'’\\s-]{2,50}$",
            "description": "User's city",
            "example": "Київ"
          },
          "birthday": {
            "type": "string",
            "format": "date-time",
            "description": "User's date of birth in ISO 8601 format",
            "example": "2010-01-19T22:00:00Z"
          },
          "file": {
            "type": "string",
            "format": "binary",
            "description": "User avatar file being uploaded (maximum size: 8 MB)"
          }
        }
      },
      "RegisterSpeakerWithApple": {
        "type": "object",
        "required": ["method", "apple_id", "role", "name", "phone", "country", "city", "activity", "file"],
        "properties": {
          "method": {
              "type": "string",
              "enum": ["apple"],
              "description": "Registration method: apple"
          },
          "apple_id": {
            "type": "string",
            "description": "User appleId"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "format": "email"
          },
          "role": {
            "type": "string",
            "enum": ["speaker"],
            "description": "User role"
          },
          "name": {
            "type": "string",
            "minLength": 2,
            "maxLength": 55,
            "description": "User name",
            "example": "Тарас Діброва"
          },
          "phone": {
            "type": "string",
            "pattern": "^\\+?\\d{1,4}?[-.\\s]?(\\(?\\d{1,4}\\)?[-.\\s]?)?\\d{1,4}[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$",
            "description": "User's phone",
            "example": "+380123456789"
          },
          "country": {
            "type": "string",
            "pattern": "^[A-Z]{2}$",
            "description": "User's country code. Must be an ISO 3166-1 alpha-2 code.",
            "example": "UA"
          },
          "city": {
            "type": "string",
            "pattern": "^[a-zA-Zа-яА-ЯґҐєЄіІїЇ'’\\s-]{2,50}$",
            "description": "User's city",
            "example": "Київ"
          },
         "activity": {
            "type": "string",
            "maxLength": 55,
            "description": "User activity",
            "example": "Фермер"
          },
          "file": {
            "type": "string",
            "format": "binary",
            "description": "User avatar file being uploaded (maximum size: 8 MB)"
          }
        }
      },
      "RegistrationWithEmailResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Message of successful sending of email for verification",
            "example": "We have sent you a verification email. Please confirm your email."
          }
        },
        "example": {
          "message": "We have sent you a verification email. Please confirm your email." 
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "User's access token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTUwMGYwOWNmNDE5ZDJiMjY4MjBiOSIsImlhdCI6MTY5MjczNTM3NiwiZXhwIjoxNjkzMzQwMTc2fQ.zy8aG3QMFs-ARrn2ji0vWJ2Rtcr65NBnz5sBT7Z8fO8"
          },
          "user": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string",
                "description": "User's id",
                "example": "7543"
              },
              "method": {
                "type": "string",
                "description": "Registration method",
                "example": "google"
              },
              "email": {
                "type": "string",
                "description": "User email",
                "example": "tarasdibrova@gmail.com"
              },
              "role": {
                "type": "string",
                "description": "User role",
                "example": "speaker"
              },
              "name": {
                "type": "string",
                "description": "User name",
                "example": "Тарас Діброва"
              },
              "phone": {
                "type": "string",
                "description": "User's phone",
                "example": "+380123456789"
              },
              "country": {
                "type": "string",
                "description": "User's country code",
                "example": "UA"
              },
              "city": {
                "type": "string",
                "description": "User's city",
                "example": "Київ"
              },
              "activity": {
                "type": "string",
                "description": "User activity",
                "example": "Фермер"
              },
              "avatar": {
                "type": "string",
                "description": "User's avatar url",
                "example": "http://res.cloudinary.com/qwsdftyuio/image/upload/qwsdfghjk/qwsdfghj.jpg"
              }
            }
          }
        },
        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTUwMGYwOWNmNDE5ZDJiMjY4MjBiOSIsImlhdCI6MTY5MjczNTM3NiwiZXhwIjoxNjkzMzQwMTc2fQ.zy8aG3QMFs-ARrn2ji0vWJ2Rtcr65NBnz5sBT7Z8fO8",
          "user": {
            "_id": "7543",
            "method": "google",
            "email": "tarasdibrova@gmail.com",
            "role": "speaker",
            "name": "Тарас Діброва",
            "phone": "+380123456789",
            "country": "UA",
            "city": "Київ",
            "activity": "Фермер",
            "avatar":  "http://res.cloudinary.com/qwsdftyuio/image/upload/qwsdfghjk/qwsdfghj.jpg"             
          }
        }
      },
      "LoginWithEmailRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User password",
            "minLength": 8,
            "maxLength": 24,
            "pattern": "^[a-zA-Z0-9]{8,24}$",
            "example": "Qw52eRty37"
          }
        }
      },
      "LoginWithEmailResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "User's access token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTUwMGYwOWNmNDE5ZDJiMjY4MjBiOSIsImlhdCI6MTY5MjczNTM3NiwiZXhwIjoxNjkzMzQwMTc2fQ.zy8aG3QMFs-ARrn2ji0vWJ2Rtcr65NBnz5sBT7Z8fO8"
          },
          "user": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string",
                "description": "User's id",
                "example": "7543"
              },
              "method": {
                "type": "string",
                "description": "Registration method",
                "example": "email"
              },
              "email": {
                "type": "string",
                "description": "User email",
                "example": "tarasdibrova@gmail.com"
              },
              "role": {
                "type": "string",
                "description": "User role",
                "example": "speaker"
              },
              "name": {
                "type": "string",
                "description": "User name",
                "example": "Тарас Діброва"
              },
              "phone": {
                "type": "string",
                "description": "User's phone",
                "example": "+380123456789"
              },
              "country": {
                "type": "string",
                "description": "User's country code",
                "example": "UA"
              },
              "city": {
                "type": "string",
                "description": "User's city",
                "example": "Київ"
              },
              "activity": {
                "type": "string",
                "description": "User activity",
                "example": "Фермер"
              },
              "avatar": {
                "type": "string",
                "description": "User's avatar url",
                "example": "http://res.cloudinary.com/qwsdftyuio/image/upload/qwsdfghjk/qwsdfghj.jpg"
              }
            }
          }
        },
        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTUwMGYwOWNmNDE5ZDJiMjY4MjBiOSIsImlhdCI6MTY5MjczNTM3NiwiZXhwIjoxNjkzMzQwMTc2fQ.zy8aG3QMFs-ARrn2ji0vWJ2Rtcr65NBnz5sBT7Z8fO8",
          "user": {
            "_id": "7543",
            "method": "email",
            "email": "tarasdibrova@gmail.com",
            "role": "speaker",
            "name": "Тарас Діброва",
            "phone": "+380123456789",
            "country": "UA",
            "city": "Київ",
            "activity": "Фермер",
            "avatar":  "http://res.cloudinary.com/qwsdftyuio/image/upload/qwsdfghjk/qwsdfghj.jpg"             
          }
        }
      },
      "LoginWithGoogleRequest": {
        "type": "object",
        "required": ["token", "platform"],
        "properties": {
          "token": {
            "type": "string",
            "description": "Google idToken"
          },
          "platform": {
            "type": "string",
            "enum": ["android", "ios"],
            "description": "User device platform"
          }
        }
      },
      "LoginWithGoogleResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "User's access token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTUwMGYwOWNmNDE5ZDJiMjY4MjBiOSIsImlhdCI6MTY5MjczNTM3NiwiZXhwIjoxNjkzMzQwMTc2fQ.zy8aG3QMFs-ARrn2ji0vWJ2Rtcr65NBnz5sBT7Z8fO8"
          },
          "user": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string",
                "description": "User's id",
                "example": "7543"
              },
              "method": {
                "type": "string",
                "description": "Registration method",
                "example": "google"
              },
              "email": {
                "type": "string",
                "description": "User email",
                "example": "tarasdibrova@gmail.com"
              },
              "role": {
                "type": "string",
                "description": "User role",
                "example": "speaker"
              },
              "name": {
                "type": "string",
                "description": "User name",
                "example": "Тарас Діброва"
              },
              "phone": {
                "type": "string",
                "description": "User's phone",
                "example": "+380123456789"
              },
              "country": {
                "type": "string",
                "description": "User's country code",
                "example": "UA"
              },
              "city": {
                "type": "string",
                "description": "User's city",
                "example": "Київ"
              },
              "activity": {
                "type": "string",
                "description": "User activity",
                "example": "Фермер"
              },
              "avatar": {
                "type": "string",
                "description": "User's avatar url",
                "example": "http://res.cloudinary.com/qwsdftyuio/image/upload/qwsdfghjk/qwsdfghj.jpg"
              }
            }
          }
        },
        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTUwMGYwOWNmNDE5ZDJiMjY4MjBiOSIsImlhdCI6MTY5MjczNTM3NiwiZXhwIjoxNjkzMzQwMTc2fQ.zy8aG3QMFs-ARrn2ji0vWJ2Rtcr65NBnz5sBT7Z8fO8",
          "user": {
            "_id": "7543",
            "method": "google",
            "email": "tarasdibrova@gmail.com",
            "role": "speaker",
            "name": "Тарас Діброва",
            "phone": "+380123456789",
            "country": "UA",
            "city": "Київ",
            "activity": "Фермер",
            "avatar":  "http://res.cloudinary.com/qwsdftyuio/image/upload/qwsdfghjk/qwsdfghj.jpg"             
          }
        }
      },
      "LoginWithGoogleAcceptedResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "The user is logged in to Google. Additional information is required to register in the application.",
            "example": "Please provide additional information to complete registration in the app." 
          },
          "data": {
            "type": "object",
            "properties": {
              "google_id": {
              "type": "string",
              "description": "User googleId",
              "example": "104292695975191234567"
              },
              "email": {
                "type": "string",
                "description": "User email",
                "example": "tarasdibrova@gmail.com"
              }
            }
          }
        },
        "example": {
          "message": "Please provide additional information to complete registration in the app.",
          "data": {
            "google_id": "104292695975191234567",
            "email": "tarasdibrova@gmail.com"
          } 
        }
      },
      "LoginWithAppleRequest": {
        "type": "object",
        "required": ["token", "platform"],
        "properties": {
          "token": {
            "type": "string",
            "description": "Apple idToken"
          },
          "platform": {
            "type": "string",
            "enum": ["ios", "android"],
            "description": "User device platform"
          }
        }
      },
      "LoginWithAppleResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "User's access token",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTUwMGYwOWNmNDE5ZDJiMjY4MjBiOSIsImlhdCI6MTY5MjczNTM3NiwiZXhwIjoxNjkzMzQwMTc2fQ.zy8aG3QMFs-ARrn2ji0vWJ2Rtcr65NBnz5sBT7Z8fO8"
          },
          "user": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string",
                "description": "User's id",
                "example": "7543"
              },
              "method": {
                "type": "string",
                "description": "Registration method",
                "example": "apple"
              },
              "email": {
                "type": "string",
                "description": "User email",
                "example": "tarasdibrova@gmail.com"
              },
              "role": {
                "type": "string",
                "description": "User role",
                "example": "speaker"
              },
              "name": {
                "type": "string",
                "description": "User name",
                "example": "Тарас Діброва"
              },
              "phone": {
                "type": "string",
                "description": "User's phone",
                "example": "+380123456789"
              },
              "country": {
                "type": "string",
                "description": "User's country code",
                "example": "UA"
              },
              "city": {
                "type": "string",
                "description": "User's city",
                "example": "Київ"
              },
              "activity": {
                "type": "string",
                "description": "User activity",
                "example": "Фермер"
              },
              "avatar": {
                "type": "string",
                "description": "User's avatar url",
                "example": "http://res.cloudinary.com/qwsdftyuio/image/upload/qwsdfghjk/qwsdfghj.jpg"
              }
            }
          }
        },
        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTUwMGYwOWNmNDE5ZDJiMjY4MjBiOSIsImlhdCI6MTY5MjczNTM3NiwiZXhwIjoxNjkzMzQwMTc2fQ.zy8aG3QMFs-ARrn2ji0vWJ2Rtcr65NBnz5sBT7Z8fO8",
          "user": {
            "_id": "7543",
            "method": "apple",
            "email": "tarasdibrova@gmail.com",
            "role": "speaker",
            "name": "Тарас Діброва",
            "phone": "+380123456789",
            "country": "UA",
            "city": "Київ",
            "activity": "Фермер",
            "avatar":  "http://res.cloudinary.com/qwsdftyuio/image/upload/qwsdfghjk/qwsdfghj.jpg"             
          }
        }
      },
      "LoginWithAppleAcceptedResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "The user is logged in to Apple. Additional information is required to register in the application.",
            "example": "Please provide additional information to complete registration in the app." 
          },
          "data": {
            "type": "object",
            "properties": {
              "apple_id": {
                "type": "string",
                "description": "User appleId",
                "example": "001345.abcde12345.fghijkl67890mnopq"
              },
              "email": {
                "type": "string",
                "description": "User email",
                "example": "tarasdibrova@gmail.com"
              }
            }
          }
        },
        "example": {
          "message": "Please provide additional information to complete registration in the app.",
          "data": {
            "apple_id": "001345.abcde12345.fghijkl67890mnopq",
            "email": "tarasdibrova@gmail.com"
          } 
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
